defmodule Brain2.Repo.Migrations.InitialSetup do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :content, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :brain_id, :uuid, null: false
    end

    create table(:emotional_states, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :level, :bigint, null: false, default: 0
      add :default_level, :bigint, null: false, default: 0
      add :prompt_injection, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :brain_id, :uuid, null: false
    end

    create table(:brains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages) do
      modify :brain_id,
             references(:brains,
               column: :id,
               name: "messages_brain_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:emotional_states) do
      modify :brain_id,
             references(:brains,
               column: :id,
               name: "emotional_states_brain_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:brains) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:brains) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:emotional_states, "emotional_states_brain_id_fkey")

    alter table(:emotional_states) do
      modify :brain_id, :uuid
    end

    drop constraint(:messages, "messages_brain_id_fkey")

    alter table(:messages) do
      modify :brain_id, :uuid
    end

    drop table(:brains)

    drop table(:emotional_states)

    drop table(:messages)
  end
end
