defmodule Brain2.Repo.Migrations.AddEmotionChanges do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:emotion_changes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :emotion_name, :text, null: false
      add :delta, :bigint, null: false
      add :from_level, :bigint, null: false
      add :to_level, :bigint, null: false
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :brain_id,
          references(:brains,
            column: :id,
            name: "emotion_changes_brain_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :thought_id,
          references(:thoughts,
            column: :id,
            name: "emotion_changes_thought_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:emotion_changes, "emotion_changes_brain_id_fkey")

    drop constraint(:emotion_changes, "emotion_changes_thought_id_fkey")

    drop table(:emotion_changes)
  end
end
